/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BlobApp {
    }
    interface BlobModeSwitch {
    }
    interface BlobModeUrl {
    }
    interface BlobOptions {
    }
}
export interface BlobModeSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLBlobModeSwitchElement;
}
declare global {
    interface HTMLBlobAppElement extends Components.BlobApp, HTMLStencilElement {
    }
    var HTMLBlobAppElement: {
        prototype: HTMLBlobAppElement;
        new (): HTMLBlobAppElement;
    };
    interface HTMLBlobModeSwitchElement extends Components.BlobModeSwitch, HTMLStencilElement {
    }
    var HTMLBlobModeSwitchElement: {
        prototype: HTMLBlobModeSwitchElement;
        new (): HTMLBlobModeSwitchElement;
    };
    interface HTMLBlobModeUrlElement extends Components.BlobModeUrl, HTMLStencilElement {
    }
    var HTMLBlobModeUrlElement: {
        prototype: HTMLBlobModeUrlElement;
        new (): HTMLBlobModeUrlElement;
    };
    interface HTMLBlobOptionsElement extends Components.BlobOptions, HTMLStencilElement {
    }
    var HTMLBlobOptionsElement: {
        prototype: HTMLBlobOptionsElement;
        new (): HTMLBlobOptionsElement;
    };
    interface HTMLElementTagNameMap {
        "blob-app": HTMLBlobAppElement;
        "blob-mode-switch": HTMLBlobModeSwitchElement;
        "blob-mode-url": HTMLBlobModeUrlElement;
        "blob-options": HTMLBlobOptionsElement;
    }
}
declare namespace LocalJSX {
    interface BlobApp {
    }
    interface BlobModeSwitch {
        "onBlobModeSelect"?: (event: BlobModeSwitchCustomEvent<BlobModeEventDetail>) => void;
    }
    interface BlobModeUrl {
    }
    interface BlobOptions {
    }
    interface IntrinsicElements {
        "blob-app": BlobApp;
        "blob-mode-switch": BlobModeSwitch;
        "blob-mode-url": BlobModeUrl;
        "blob-options": BlobOptions;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blob-app": LocalJSX.BlobApp & JSXBase.HTMLAttributes<HTMLBlobAppElement>;
            "blob-mode-switch": LocalJSX.BlobModeSwitch & JSXBase.HTMLAttributes<HTMLBlobModeSwitchElement>;
            "blob-mode-url": LocalJSX.BlobModeUrl & JSXBase.HTMLAttributes<HTMLBlobModeUrlElement>;
            "blob-options": LocalJSX.BlobOptions & JSXBase.HTMLAttributes<HTMLBlobOptionsElement>;
        }
    }
}
