/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BlobApp {
    }
    interface BlobOptions {
        "getArgs": () => Promise<string[]>;
    }
}
declare global {
    interface HTMLBlobAppElement extends Components.BlobApp, HTMLStencilElement {
    }
    var HTMLBlobAppElement: {
        prototype: HTMLBlobAppElement;
        new (): HTMLBlobAppElement;
    };
    interface HTMLBlobOptionsElement extends Components.BlobOptions, HTMLStencilElement {
    }
    var HTMLBlobOptionsElement: {
        prototype: HTMLBlobOptionsElement;
        new (): HTMLBlobOptionsElement;
    };
    interface HTMLElementTagNameMap {
        "blob-app": HTMLBlobAppElement;
        "blob-options": HTMLBlobOptionsElement;
    }
}
declare namespace LocalJSX {
    interface BlobApp {
    }
    interface BlobOptions {
    }
    interface IntrinsicElements {
        "blob-app": BlobApp;
        "blob-options": BlobOptions;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "blob-app": LocalJSX.BlobApp & JSXBase.HTMLAttributes<HTMLBlobAppElement>;
            "blob-options": LocalJSX.BlobOptions & JSXBase.HTMLAttributes<HTMLBlobOptionsElement>;
        }
    }
}
